content:
  - name: posts
    label: Blog Posts
    path: src/content/post
    type: collection
    filename: "{primary}.md"
    view:
      fields: [title, date, draft]
      primary: title
      sort: [date, desc]
    fields:
      - name: title
        label: Título
        type: string
        required: true

      - name: description
        label: Descrição
        type: string
        required: true

      - name: date
        label: Data de publicação
        type: date
        required: true

      - name: draft
        label: Rascunho
        type: boolean
        default: false

      - name: image
        label: Imagem de capa
        type: image

      - name: tags
        label: Tags
        type: string
        list: true

      - name: body
        label: Conteúdo
        type: rich-text

  - name: pages
    label: Páginas
    path: src/content/page
    type: collection
    filename: "{primary}.md"
    view:
      fields: [title]
      primary: title
    fields:
      - name: title
        label: Título
        type: string
        required: true

      - name: description
        label: Descrição
        type: string

      - name: body
        label: Conteúdo
        type: rich-text

media:

  input: public/images

  output: /images